Repository Elias-Manica/Linkr-front, pull requests merged in 2022-10, with the labels that each got.

#1 feat: implemented sign-up page
  package-lock.json
  package.json
  public/index.html
  src/assets/css/GlobalStyle.js
  src/screens/App.js
  src/screens/SignUpScreen/SignUpScreen.js
  src/screens/SignUpScreen/styles.js
  src/services/linkrService.js
Labels: enhancement

#4 Feat/login
  public/index.html
  src/screens/App.js
  src/screens/LoginScreen/LoginScreen.js
  src/screens/LoginScreen/styles.js
  src/services/linkrService.js
Labels: enhancement

#5 Feat/searchUsers : funcionality complete
  package-lock.json
  package.json
  src/components/UserPosts.js/UserPosts.js
  src/components/UserPosts.js/UserSearchInfo.js
  src/screens/App.js
  src/screens/UserPostsScreen/UserPostsScreen.js
  src/screens/UserPostsScreen/styles.js
  src/services/linkrService.js
Labels: enhancement

#6 Feat/logout and Topbar
  package-lock.json
  package.json
  src/Components/TopBar/TopBar.js
  src/Components/TopBar/styles.js
  src/contexts/UserContext.js
  src/screens/LoginScreen/LoginScreen.js
  src/screens/SignUpScreen/SignUpScreen.js
  src/screens/TimelineScreen/TimelineScreen.js
  src/services/linkrService.js
Labels: enhancement

#11 Feat/go to user
  package-lock.json
  src/Components/PostUser/PostUser.js
  src/Components/TopBar/TopBar.js
  src/Components/TopBar/styles.js
  src/Components/UserSearchInfo/UserSearchInfo.js
  src/components/UserPosts.js/UserPosts.js
  src/screens/TimelineScreen/TimelineScreen.js
  src/screens/UserPostsScreen/UserPostsScreen.js
  src/screens/UserPostsScreen/styles.js
  src/services/linkrService.js
  src/services/postService.js
Labels: enhancement

#17 alterei a URL do axios nas funções de like e dislike para funcionar n…
  src/services/postService.js
Labels: bugfix

#19 Feat/auth
  src/Components/TopBar/TopBar.js
  src/screens/App.js
  src/screens/NewPost/NewPost.js
  src/screens/NewPost/style.js
  src/services/linkrService.js
Labels: enhancement, bugfix

#21 Feat/comment post
  src/Components/PostUser/PostUser.js
  src/Components/PostUser/styles.js
  src/screens/NewPost/style.js
  src/screens/Post/Post.js
  src/screens/Post/style.js
  src/services/postService.js
Labels: enhancement

#23 bugfix: now the function to post a comment it's running properly
  src/Components/Comments/Comments.js
  src/Components/PostUser/PostUser.js
  src/services/postService.js
Labels: bugfix

#25 fix: changing LOCAL_HOST to BASE_URL
  src/services/postService.js
Labels: bugfix

#27 Feat/show following posts
  package-lock.json
  src/screens/TimelineScreen/TimelineScreen.js
  src/services/linkrService.js
  src/services/postService.js
Labels: enhancement

#28 Feat/repost
  src/Components/ModalRepost/ModalRepost.js
  src/Components/ModalRepost/styles.js
  src/Components/PostUser/PostUser.js
  src/Components/PostUser/styles.js
  src/screens/LoginScreen/LoginScreen.js
  src/services/postService.js
Labels: enhancement
